using System;
using System.Collections.Generic;
using System.Linq;

/*
 * How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?
 */
namespace ProjectEuler
{
    class Euler29 : EulerProblem
    {
        public override object Solution()
        {
            // hash set removes duplicates
            return new HashSet<double>(GetTerms()).Count;
        }

        public IEnumerable<double> GetTerms()
        {
            foreach (int a in Enumerable.Range(2, 99))
            {
                foreach (int b in Enumerable.Range(2, 99))
                {
                    yield return Math.Pow(a, b);
                }
            }
        }
    }
}
